INSERT INTO AULA (NUMERO, NOMBRE, CAPACIDAD, PLANTA, DESCRIPCION) VALUES (12, 'IAW' 22, 1, 'Clase de Iaw');
INSERT INTO USUARIO (nombre, apellidos, edad, Direccion, matriculado) VALUES ('Jose', 'Ropero', 18, 'C/ Sevilla, Nº1','Informática');
INSERT INTO CURSO VALUES(1,'Raúl','Inscripción de Raúl en el primer curso','400')
INSERT INTO EDIFICIO (NOMBRE, DESCRIPCION) VALUES ("pepito", "localizado cerca del paseo maritimo")