UPDATE AULA SET nombre = 'ASO' WHERE NOMBRE LIKE 'IAW';

UPDATE USUARIO SET edad = 21 WHERE nombre LIKE 'Jose';

UPDATE CURSO 
SET nombre = 'David'
WHERE nombre LIKE 'Raúl';

UPDATE EDIFICIO
SET NOMBRE = "COSTA"
WHERE NOMBRE LIKE "pepito";